# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '3.0.100-preview4-010538'

- script: dotnet test dotnet/tests/Spreads.Native.Tests.NuGet/Spreads.Native.Tests.NuGet.csproj -c Debug --framework=net461  -v m
  displayName: 'Test Debug'
- script: dotnet test dotnet/tests/Spreads.Native.Tests.NuGet/Spreads.Native.Tests.NuGet.csproj -c Release --framework=net461 -v m
  displayName: 'Test Release'
- script: dotnet test dotnet/tests/Spreads.Native.Tests.NuGet/Spreads.Native.Tests.NuGet.csproj -c Debug --framework=netcoreapp3.0 -v m
  displayName: 'Test Debug'
- script: dotnet test dotnet/tests/Spreads.Native.Tests.NuGet/Spreads.Native.Tests.NuGet.csproj -c Release --framework=netcoreapp3.0 -v m
  displayName: 'Test Release'